In [1]:
import numpy as np
import pandas as pd
import viz
np.random.seed(22)

## 1. How likely is it that you roll doubles when rolling two dice?

In [2]:
die1 = np.random.choice([1,2,3,4,5,6], 10000)
die2 = np.random.choice([1,2,3,4,5,6], 10000)

doubles = die1 == die2
doubles

array([ True, False, False, ...,  True, False, False])

In [3]:
doubles.mean()

0.1682

## 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

### 2A) Probability of getting 3 heads

In [4]:
n_trials = nrows = 10000
n_dice = ncols = 8

coins = np.random.choice([0,1],size=(nrows,ncols))
coins

array([[0, 0, 1, ..., 1, 0, 0],
       [1, 1, 1, ..., 0, 1, 0],
       [0, 1, 1, ..., 1, 1, 0],
       ...,
       [0, 0, 0, ..., 1, 1, 0],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 0, 0, 0]])

In [5]:
coins_sum = coins.sum(axis=1)
coins_sum

array([4, 5, 4, ..., 4, 6, 5])

In [6]:
heads_3 = coins_sum == 3
heads_3.mean()

0.2199

In [7]:
### 2B Probability of getting more than 3 heads

In [8]:
heads_3more = coins_sum > 3
heads_3more.mean()

0.6355

## 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [13]:
n_trials = nrows = 10000
n_cohorts = ncols = 2

billboards = np.random.choice(['ds','web1','web2','web3'], size=(n_trials, n_cohorts))
billboards

array([['web1', 'web3'],
       ['web3', 'web2'],
       ['web3', 'web3'],
       ...,
       ['ds', 'web3'],
       ['web3', 'ds'],
       ['web2', 'web1']], dtype='<U4')

In [14]:
billboards = pd.DataFrame(billboards)
billboards.head()

0     1
0  web1  web3
1  web3  web2
2  web3  web3
3  web3  web2
4  web2  web1

In [26]:
((billboards[0] == 'ds') & (billboards[1] == 'ds')).mean()

0.0629

## 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [31]:
#build normal distribution array for poptarts
poptarts = np.random.normal(3,1.5, size=(10000, 5)).astype(int)
poptarts

array([[1, 4, 1, 0, 2],
       [2, 3, 3, 3, 1],
       [3, 6, 1, 1, 2],
       ...,
       [1, 4, 5, 3, 4],
       [1, 2, 2, 4, 1],
       [4, 0, 2, 2, 3]])

In [32]:
#build dataframe
poptarts = pd.DataFrame(poptarts, columns=['Monday','Tuesday','Wednesday','Thursday','Friday'])
poptarts.head()

Monday  Tuesday  Wednesday  Thursday  Friday
0       1        4          1         0       2
1       2        3          3         3       1
2       3        6          1         1       2
3       2        2          3         3       2
4       0        4          5         3       1

In [33]:
# Add Column for sum of the week
poptarts['week_sum'] = poptarts.sum(axis=1)
poptarts

Monday  Tuesday  Wednesday  Thursday  Friday  week_sum
0          1        4          1         0       2         8
1          2        3          3         3       1        12
2          3        6          1         1       2        13
3          2        2          3         3       2        12
4          0        4          5         3       1        13
...      ...      ...        ...       ...     ...       ...
9995       2        2          4         5       3        16
9996       3        4          1         4       3        15
9997       1        4          5         3       4        17
9998       1        2          2         4       1        10
9999       4        0          2         2       3        11

[10000 rows x 6 columns]

In [34]:
# Add Boolean Column for if there is poptart left on Friday
poptarts['poptarts_left'] = poptarts.week_sum < 17
poptarts

Monday  Tuesday  Wednesday  Thursday  Friday  week_sum  poptarts_left
0          1        4          1         0       2         8           True
1          2        3          3         3       1        12           True
2          3        6          1         1       2        13           True
3          2        2          3         3       2        12           True
4          0        4          5         3       1        13           True
...      ...      ...        ...       ...     ...       ...            ...
9995       2        2          4         5       3        16           True
9996       3        4          1         4       3        15           True
9997       1        4          5         3       4        17          False
9998       1        2          2         4       1        10           True
9999       4        0          2         2       3        11           True

[10000 rows x 7 columns]

In [35]:
# probability that there will be poptarts left on Friday
poptarts.poptarts_left.mean()

0.8786

## 5. Compare Heights
    * Men have an average height of 178 cm and standard deviation of 8cm.
    * Women have a mean of 170, sd = 6cm.
    * Since you have means and standard deviations, you can use np.random.normal to generate observations.
    * If a man and woman are chosen at random, P(woman taller than man)?

In [37]:
male_height = np.random.normal(178,8,10000).astype(int)
male_height

array([173, 178, 183, ..., 177, 174, 162])

In [38]:
female_height = np.random.normal(170,6,10000).astype(int)
female_height

array([167, 170, 167, ..., 173, 170, 175])

In [39]:
gender_heights = pd.DataFrame({'male_height':male_height,
                               'female_height':female_height})
gender_heights

male_height  female_height
0             173            167
1             178            170
2             183            167
3             177            161
4             175            175
...           ...            ...
9995          173            182
9996          167            176
9997          177            173
9998          174            170
9999          162            175

[10000 rows x 2 columns]

In [40]:
gender_heights['female_taller'] = female_height > male_height
gender_heights

male_height  female_height  female_taller
0             173            167          False
1             178            170          False
2             183            167          False
3             177            161          False
4             175            175          False
...           ...            ...            ...
9995          173            182           True
9996          167            176           True
9997          177            173          False
9998          174            170          False
9999          162            175           True

[10000 rows x 3 columns]

In [41]:
gender_heights.female_taller.mean()

0.201

## 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
What is the probability that we observe an installation issue within the first 150 students that download anaconda?
How likely is it that 450 students all download anaconda without an issue?

### What are the odds that after having 50 students download anaconda, no one has an installation issue?

In [42]:
# Setup fail array, 
p_fail = 1/250
p_pass = 249/250
n_computers = 50
n_trials = 10_000

computers = np.random.choice([0,1], p=[p_pass,p_fail], size=(n_trials,n_computers))
computers = pd.DataFrame(computers)
computers.head()


0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  46  \
0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

   47  48  49  
0   0   0   0  
1   0   0   0  
2   0   0   0  
3   0   0   0  
4   0   0   0  

[5 rows x 50 columns]

In [43]:
# Created sum of fails
computers['fail_sum'] = computers.sum(axis=1)
computers.head()

0  1  2  3  4  5  6  7  8  9  ...  41  42  43  44  45  46  47  48  49  \
0  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
1  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
2  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
3  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
4  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   

   fail_sum  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 51 columns]

In [44]:
# Probablity of of no fails
p_comp_pass = (computers.fail_sum == 0).mean()
p_comp_pass

0.8154

### Probability of No Fails (Pass) with 100 Students

In [45]:
# updated computer to 100
p_fail = 1/250
p_pass = 249/250
n_computers = 100
n_trials = 10_000

computers = np.random.choice([0,1], p=[p_pass,p_fail], size=(n_trials,n_computers))
computers = pd.DataFrame(computers)
computers['fail_sum'] = computers.sum(axis=1)
p_comp_pass = (computers.fail_sum == 0).mean()
p_comp_pass

0.6684

### What is the probability that we observe an installation issue within the first 150 students that download anaconda?


In [46]:
# updated computer to 150
p_fail = 1/250
p_pass = 249/250
n_computers = 150
n_trials = 10_000

computers = np.random.choice([0,1], p=[p_pass,p_fail], size=(n_trials,n_computers))
computers = pd.DataFrame(computers)
computers['fail_sum'] = computers.sum(axis=1)
p_comp_pass = (computers.fail_sum == 0).mean()
p_comp_pass

0.5525

In [47]:
p_comp_fail  = 1 - p_comp_pass
p_comp_fail

0.4475

### How likely is it that 450 students all download anaconda without an issue?

In [48]:
# updated computer to 450
p_fail = 1/250
p_pass = 249/250
n_computers = 450
n_trials = 10_000

computers = np.random.choice([0,1], p=[p_pass,p_fail], size=(n_trials,n_computers))
computers = pd.DataFrame(computers)
computers['fail_sum'] = computers.sum(axis=1)
p_comp_pass = (computers.fail_sum == 0).mean()
p_comp_pass

0.1632

## 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?
How likely is it that a food truck will show up sometime this week?

In [52]:
p_truck = .7
p_no_truck = .3

truck = np.random.choice([0,1],p=[p_no_truck, p_truck], size=(10_000,3))
truck = pd.DataFrame(truck)
truck

0  1  2
0     1  0  1
1     1  0  1
2     1  1  0
3     1  1  1
4     1  1  0
...  .. .. ..
9995  0  1  1
9996  1  1  0
9997  1  1  1
9998  1  0  1
9999  0  1  1

[10000 rows x 3 columns]

In [53]:
truck['truck_sum'] = truck.sum(axis=1)
truck

0  1  2  truck_sum
0     1  0  1          2
1     1  0  1          2
2     1  1  0          2
3     1  1  1          3
4     1  1  0          2
...  .. .. ..        ...
9995  0  1  1          2
9996  1  1  0          2
9997  1  1  1          3
9998  1  0  1          2
9999  0  1  1          2

[10000 rows x 4 columns]

In [57]:
no_truck = (truck.truck_sum == 0).mean()
no_truck

0.026

In [60]:
truck = np.random.choice([0,1],p=[p_no_truck, p_truck], size=(10_000,5))
truck = pd.DataFrame(truck)
truck['truck_sum'] = truck.sum(axis=1)
no_truck = (truck.truck_sum == 0).mean()
no_truck

0.0023

In [61]:
yes_truck = 1 - no_truck
yes_truck

0.9977

## 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [71]:
n_trials = 10_000
bdays = list(range(1,366))
people = 23

people_bdays = np.random.choice(bdays, size=(n_trials, people))
people_bdays
df = pd.DataFrame(people_bdays, columns=list(range(1, people + 1)))
df.head()

1    2    3    4    5    6    7    8    9    10  ...   14   15   16   17  \
0  298  138  142  338   39  291   53   85  275  313  ...   33  344  312  302   
1  113  340  208   47   87   86  361    4   86  205  ...   45   99  210  115   
2  244  111  204  174  179  142  346   33  117   44  ...  290  347   29  306   
3   13  326  223  361   70  321  243   95  119  175  ...  168  253  212  150   
4   52   62  264  210  203  135  125  198  227  316  ...  113    7  269  351   

    18   19   20   21   22   23  
0  106  107   22  173  228   24  
1  170  250  239  259   47  112  
2  237  304  139   37  321  224  
3   80  138  107  247  179  134  
4  337  288   28  209   23   61  

[5 rows x 23 columns]

In [75]:
(df.nunique(axis=1) < people).mean()

0.5095

In [76]:
## for 20 People
n_trials = 10_000
bdays = list(range(1,366))
people = 20

people_bdays = np.random.choice(bdays, size=(n_trials, people))
people_bdays
df = pd.DataFrame(people_bdays, columns=list(range(1, people + 1)))
(df.nunique(axis=1) < people).mean()

0.4095

In [77]:
## for 40 People
n_trials = 10_000
bdays = list(range(1,366))
people = 40

people_bdays = np.random.choice(bdays, size=(n_trials, people))
people_bdays
df = pd.DataFrame(people_bdays, columns=list(range(1, people + 1)))
(df.nunique(axis=1) < people).mean()

0.8928