In [1]:
import numpy as np
import pandas as pd
import viz
np.random.seed(22)

## 1. How likely is it that you roll doubles when rolling two dice?

In [2]:
die1 = np.random.choice([1,2,3,4,5,6], 10000)
die2 = np.random.choice([1,2,3,4,5,6], 10000)

doubles = die1 == die2
doubles

array([ True, False, False, ...,  True, False, False])

In [3]:
doubles.mean()

0.1682

## 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

### 2A) Probability of getting 3 heads

In [76]:
n_trials = nrows = 10000
n_dice = ncols = 8

coins = np.random.choice([0,1],size=(nrows,ncols))
coins

array([[1, 1, 0, ..., 0, 1, 1],
       [1, 0, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [1, 1, 0, ..., 1, 1, 1],
       [0, 0, 1, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 0]])

In [77]:
coins_sum = coins.sum(axis=1)
coins_sum

array([4, 4, 3, ..., 6, 4, 2])

In [6]:
heads_3 = coins_sum == 3
heads_3.mean()

0.2199

In [7]:
### 2B Probability of getting more than 3 heads

In [73]:
heads_3more = coins_sum > 3
heads_3more.mean()

0.6355

## 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [9]:
.25 * .25

0.0625

In [78]:
1 -(.75*.75)

0.4375

In [10]:
n_trials = nrows = 10000
n_cohorts = ncols = 4

billboards = np.random.choice(['ds','web1','web2','web3'], size=(n_trials, n_cohorts))
billboards

array([['web3', 'ds', 'web1', 'web3'],
       ['web2', 'web2', 'web1', 'web3'],
       ['ds', 'web1', 'ds', 'web1'],
       ...,
       ['web2', 'ds', 'web1', 'web3'],
       ['web1', 'ds', 'web1', 'web3'],
       ['ds', 'web1', 'ds', 'ds']], dtype='<U4')

In [11]:
billboards = pd.DataFrame(billboards, columns=(['opt1','opt2','opt3','opt4']))
billboards.head()

opt1  opt2  opt3  opt4
0  web3    ds  web1  web3
1  web2  web2  web1  web3
2    ds  web1    ds  web1
3    ds  web2  web1  web1
4  web3  web2  web1  web1

In [12]:
def count_ds(row):
    return row.opt1.count("ds") + row.opt2.count("ds") + row.opt3.count("ds") + row.opt4.count("ds")

In [13]:
billboards['ds_count'] = billboards.apply(count_ds, axis=1)
billboards.head()

opt1  opt2  opt3  opt4  ds_count
0  web3    ds  web1  web3         1
1  web2  web2  web1  web3         0
2    ds  web1    ds  web1         2
3    ds  web2  web1  web1         1
4  web3  web2  web1  web1         0

In [14]:
(billboards.ds_count == 2).mean()

0.2188

## 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [15]:
#build normal distribution array for poptarts
poptarts = np.random.normal(3,1.5, (10000, 5))
poptarts

array([[ 2.66824583,  3.72299631,  4.18754245,  3.30580776,  2.04580797],
       [-0.36615282,  2.05210768,  4.61678579,  3.84927155,  3.29239677],
       [ 2.07909875,  0.33473529,  2.66742939,  2.03188987,  1.96100431],
       ...,
       [ 4.57564726,  3.65676126,  3.23878835,  2.71076551,  0.48011121],
       [-0.18850146,  4.30358201,  1.70234654,  4.46191548,  4.15135184],
       [ 4.08405768,  5.57620371,  6.14272467,  1.65225318,  3.26275068]])

In [16]:
#build dataframe
poptarts = pd.DataFrame(poptarts, columns=['Monday','Tuesday','Wednesday','Thursday','Friday'])
poptarts.head()

Monday   Tuesday  Wednesday  Thursday    Friday
0  2.668246  3.722996   4.187542  3.305808  2.045808
1 -0.366153  2.052108   4.616786  3.849272  3.292397
2  2.079099  0.334735   2.667429  2.031890  1.961004
3  3.998727  0.997405   3.303948  2.640008  5.063706
4  2.964667  1.482641   3.337869 -0.153282  3.144717

In [17]:
# Add Column for sum of the week
poptarts['week_sum'] = poptarts.sum(axis=1)
poptarts

Monday   Tuesday  Wednesday  Thursday    Friday   week_sum
0     2.668246  3.722996   4.187542  3.305808  2.045808  15.930400
1    -0.366153  2.052108   4.616786  3.849272  3.292397  13.444409
2     2.079099  0.334735   2.667429  2.031890  1.961004   9.074158
3     3.998727  0.997405   3.303948  2.640008  5.063706  16.003794
4     2.964667  1.482641   3.337869 -0.153282  3.144717  10.776612
...        ...       ...        ...       ...       ...        ...
9995  1.178039  0.896992   2.806042  2.700536  2.803766  10.385376
9996  2.155662  5.423620   0.367417  1.785323  2.527843  12.259864
9997  4.575647  3.656761   3.238788  2.710766  0.480111  14.662074
9998 -0.188501  4.303582   1.702347  4.461915  4.151352  14.430694
9999  4.084058  5.576204   6.142725  1.652253  3.262751  20.717990

[10000 rows x 6 columns]

In [18]:
# Add Boolean Column for if there is poptart left on Friday
poptarts['poptarts_left'] = poptarts.week_sum < 17
poptarts

Monday   Tuesday  Wednesday  Thursday    Friday   week_sum  \
0     2.668246  3.722996   4.187542  3.305808  2.045808  15.930400   
1    -0.366153  2.052108   4.616786  3.849272  3.292397  13.444409   
2     2.079099  0.334735   2.667429  2.031890  1.961004   9.074158   
3     3.998727  0.997405   3.303948  2.640008  5.063706  16.003794   
4     2.964667  1.482641   3.337869 -0.153282  3.144717  10.776612   
...        ...       ...        ...       ...       ...        ...   
9995  1.178039  0.896992   2.806042  2.700536  2.803766  10.385376   
9996  2.155662  5.423620   0.367417  1.785323  2.527843  12.259864   
9997  4.575647  3.656761   3.238788  2.710766  0.480111  14.662074   
9998 -0.188501  4.303582   1.702347  4.461915  4.151352  14.430694   
9999  4.084058  5.576204   6.142725  1.652253  3.262751  20.717990   

      poptarts_left  
0              True  
1              True  
2              True  
3              True  
4              True  
...             ...  
9995           True  
9996           True  
9997           True  
9998           True  
9999          False  

[10000 rows x 7 columns]

In [19]:
# probability that there will be poptarts left on Friday
poptarts.poptarts_left.mean()

0.7277

## 5. Compare Heights
    * Men have an average height of 178 cm and standard deviation of 8cm.
    * Women have a mean of 170, sd = 6cm.
    * Since you have means and standard deviations, you can use np.random.normal to generate observations.
    * If a man and woman are chosen at random, P(woman taller than man)?

In [20]:
male_height = np.random.normal(178,8,10000)
male_height

array([191.27461775, 175.5594152 , 181.37001654, ..., 166.92400752,
       177.09279937, 177.510554  ])

In [21]:
female_height = np.random.normal(170,6,10000)
female_height

array([174.20020797, 169.2762629 , 161.43512083, ..., 173.49023316,
       174.7976375 , 181.18542023])

In [22]:
gender_heights = pd.DataFrame({'male_height':male_height,
                               'female_height':female_height})
gender_heights

male_height  female_height
0      191.274618     174.200208
1      175.559415     169.276263
2      181.370017     161.435121
3      168.786891     177.906174
4      173.263551     173.251181
...           ...            ...
9995   180.437465     165.484846
9996   183.271695     171.474725
9997   166.924008     173.490233
9998   177.092799     174.797638
9999   177.510554     181.185420

[10000 rows x 2 columns]

In [23]:
gender_heights['female_taller'] = female_height > male_height
gender_heights

male_height  female_height  female_taller
0      191.274618     174.200208          False
1      175.559415     169.276263          False
2      181.370017     161.435121          False
3      168.786891     177.906174           True
4      173.263551     173.251181          False
...           ...            ...            ...
9995   180.437465     165.484846          False
9996   183.271695     171.474725          False
9997   166.924008     173.490233           True
9998   177.092799     174.797638          False
9999   177.510554     181.185420           True

[10000 rows x 3 columns]

In [24]:
gender_heights.female_taller.mean()

0.2175

## 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
What is the probability that we observe an installation issue within the first 150 students that download anaconda?
How likely is it that 450 students all download anaconda without an issue?

### What are the odds that after having 50 students download anaconda, no one has an installation issue?

In [39]:
# Setup fail array, 
p_fail = 1/250
p_pass = 249/250
n_computers = 50
n_trials = 10_000

computers = np.random.choice([0,1], p=[p_pass,p_fail], size=(n_trials,n_computers))
computers = pd.DataFrame(computers)
computers.head()


0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  46  \
0   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
2   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
3   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
4   0   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   

   47  48  49  
0   0   0   0  
1   0   0   0  
2   0   0   0  
3   0   0   0  
4   0   0   0  

[5 rows x 50 columns]

In [48]:
# Created sum of fails
computers['fail_sum'] = computers.sum(axis=1)
computers.head()

0  1  2  3  4  5  6  7  8  9  ...  41  42  43  44  45  46  47  48  49  \
0  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
1  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
2  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
3  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   
4  0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   0   

   fail_sum  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 51 columns]

In [56]:
# Probablity of of no fails
p_comp_pass = (computers.fail_sum == 0).mean()
p_comp_pass

0.5403

### Probability of No Fails (Pass) with 100 Students

In [57]:
# updated computer to 100
p_fail = 1/250
p_pass = 249/250
n_computers = 100
n_trials = 10_000

computers = np.random.choice([0,1], p=[p_pass,p_fail], size=(n_trials,n_computers))
computers = pd.DataFrame(computers)
computers['fail_sum'] = computers.sum(axis=1)
p_comp_pass = (computers.fail_sum == 0).mean()
p_comp_pass

0.6737

### What is the probability that we observe an installation issue within the first 150 students that download anaconda?


In [58]:
# updated computer to 150
p_fail = 1/250
p_pass = 249/250
n_computers = 150
n_trials = 10_000

computers = np.random.choice([0,1], p=[p_pass,p_fail], size=(n_trials,n_computers))
computers = pd.DataFrame(computers)
computers['fail_sum'] = computers.sum(axis=1)
p_comp_pass = (computers.fail_sum == 0).mean()
p_comp_pass

0.5449

In [59]:
p_comp_fail  = 1 - p_comp_pass
p_comp_fail

0.45509999999999995

### How likely is it that 450 students all download anaconda without an issue?

In [70]:
# updated computer to 450
p_fail = 1/250
p_pass = 249/250
n_computers = 450
n_trials = 10_000

computers = np.random.choice([0,1], p=[p_pass,p_fail], size=(n_trials,n_computers))
computers = pd.DataFrame(computers)
computers['fail_sum'] = computers.sum(axis=1)
p_comp_pass = (computers.fail_sum == 0).mean()
p_comp_pass

0.1614

In [71]:
p_comp_fail  = 1 - p_comp_pass
p_comp_fail

0.8386

In [68]:
1-((249/250)**450)

0.8352967038413871

## 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?
How likely is it that a food truck will show up sometime this week?

## 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?